@extends('_layouts.sample')

@section('pagecontent')
    <div class="container relative mx-auto max-w-1166 pt-6">
        <x-exemple-retour/>
        <x-exemple
            title1="Exemples"
            title2="pièces<br>salées<br>maison" 
            title_image="/assets/img/exemples/sales/sale-header.png"
            image01="/assets/img/exemples/sales/sale-01.png"
            image02="/assets/img/exemples/sales/sale-02.png"
            image03="/assets/img/exemples/sales/sale-03.png"
            image04="/assets/img/exemples/sales/sale-04.png"
            image05="/assets/img/exemples/sales/sale-05.png"
            image06="/assets/img/exemples/sales/sale-06.png"
            image07="/assets/img/exemples/sales/sale-07.png"
            image08="/assets/img/exemples/sales/sale-08.png"
            image09="/assets/img/exemples/sales/sale-09.png"
            image10="/assets/img/exemples/sales/sale-10.png"
            image11=""
            image12=""/>
        <x-exemple
            title1="Exemples"
            title2="pièces<br>sucrées<br>maison" 
            title_image="/assets/img/exemples/sucres/sucre-header.png"
            image01="/assets/img/exemples/sucres/sucre-01.png"
            image02="/assets/img/exemples/sucres/sucre-02.png"
            image03="/assets/img/exemples/sucres/sucre-03.png"
            image04="/assets/img/exemples/sucres/sucre-04.png"
            image05="/assets/img/exemples/sucres/sucre-05.png"
            image06="/assets/img/exemples/sucres/sucre-06.png"
            image07="/assets/img/exemples/sucres/sucre-07.png"
            image08="/assets/img/exemples/sucres/sucre-08.png"
            image09="/assets/img/exemples/sucres/sucre-09.png"
            image10="/assets/img/exemples/sucres/sucre-10.png"
            image11=""
            image12=""/>
        <x-exemple
            title1="Exemples"
            title2="entrées<br>plats &<br>desserts" 
            title_image="/assets/img/exemples/repas/repas-header.png"
            image01="/assets/img/exemples/repas/repas-01.png"
            image02="/assets/img/exemples/repas/repas-02.png"
            image03="/assets/img/exemples/repas/repas-03.png"
            image04="/assets/img/exemples/repas/repas-04.png"
            image05="/assets/img/exemples/repas/repas-05.png"
            image06="/assets/img/exemples/repas/repas-06.png"
            image07="/assets/img/exemples/repas/repas-07.png"
            image08="/assets/img/exemples/repas/repas-08.png"
            image09="/assets/img/exemples/repas/repas-09.png"
            image10="/assets/img/exemples/repas/repas-10.png"
            image11=""
            image12=""/>
        <x-exemple 
            title1="Exemples"
            title2="de<br>buffets"
            title_image="/assets/img/exemples/buffets/buffet-header.png"
            image01="/assets/img/exemples/buffets/buffet-01.png"
            image02="/assets/img/exemples/buffets/buffet-02.png"
            image03="/assets/img/exemples/buffets/buffet-03.png"
            image04="/assets/img/exemples/buffets/buffet-04.png"
            image05="/assets/img/exemples/buffets/buffet-05.png"
            image06="/assets/img/exemples/buffets/buffet-06.png"
            image07="/assets/img/exemples/buffets/buffet-07.png"
            image08="/assets/img/exemples/buffets/buffet-08.png"
            image09="/assets/img/exemples/buffets/buffet-09.png"
            image10="/assets/img/exemples/buffets/buffet-10.png"
            image11=""
            image12=""/>
    </div>
    <x-exemple-devis :page="$page"/>
@endsection
