@extends('_layouts.sample')

@section('pagecontent')
    <div class="container relative mx-auto max-w-1166 pt-6">
        <x-exemple-retour/>
        <x-exemple
            title1="Exemples"
            title2="pièces<br>salées<br>maison" 
            title_image="/assets/img/exemples/sales/sale-header.webp"
            image01="/assets/img/exemples/sales/sale-01.webp"
            image02="/assets/img/exemples/sales/sale-02.webp"
            image03="/assets/img/exemples/sales/sale-03.webp"
            image04="/assets/img/exemples/sales/sale-04.webp"
            image05="/assets/img/exemples/sales/sale-05.webp"
            image06="/assets/img/exemples/sales/sale-06.webp"
            image07="/assets/img/exemples/sales/sale-07.webp"
            image08="/assets/img/exemples/sales/sale-08.webp"
            image09="/assets/img/exemples/sales/sale-09.webp"
            image10="/assets/img/exemples/sales/sale-10.webp"
            image11=""
            image12=""/>
        <x-exemple
            title1="Exemples"
            title2="pièces<br>sucrées<br>maison" 
            title_image="/assets/img/exemples/sucres/sucre-header.webp"
            image01="/assets/img/exemples/sucres/sucre-01.webp"
            image02="/assets/img/exemples/sucres/sucre-02.webp"
            image03="/assets/img/exemples/sucres/sucre-03.webp"
            image04="/assets/img/exemples/sucres/sucre-04.webp"
            image05="/assets/img/exemples/sucres/sucre-05.webp"
            image06="/assets/img/exemples/sucres/sucre-06.webp"
            image07="/assets/img/exemples/sucres/sucre-07.webp"
            image08="/assets/img/exemples/sucres/sucre-08.webp"
            image09="/assets/img/exemples/sucres/sucre-09.webp"
            image10="/assets/img/exemples/sucres/sucre-10.webp"
            image11=""
            image12=""/>
        <x-exemple
            title1="Exemples"
            title2="entrées<br>plats &<br>desserts" 
            title_image="/assets/img/exemples/repas/repas-header-part.webp"
            image01="/assets/img/exemples/repas/repas-01.webp"
            image02="/assets/img/exemples/repas/repas-02.webp"
            image03="/assets/img/exemples/repas/repas-03.webp"
            image04="/assets/img/exemples/repas/repas-04.webp"
            image05="/assets/img/exemples/repas/repas-05-part.webp"
            image06="/assets/img/exemples/repas/repas-06-part.webp"
            image07="/assets/img/exemples/repas/repas-07-part.webp"
            image08="/assets/img/exemples/repas/repas-08.webp"
            image09="/assets/img/exemples/repas/repas-09.webp"
            image10="/assets/img/exemples/repas/repas-10.webp"
            image11=""
            image12=""/>
        <x-exemple 
            title1="Exemples"
            title2="mises de<br>tables"
            title_image="/assets/img/exemples/tables/table-header.webp"
            image01="/assets/img/exemples/tables/table-01.webp"
            image02="/assets/img/exemples/tables/table-02.webp"
            image03="/assets/img/exemples/tables/table-03.webp"
            image04="/assets/img/exemples/tables/table-04.webp"
            image05="/assets/img/exemples/tables/table-05.webp"
            image06="/assets/img/exemples/tables/table-06.webp"
            image07="/assets/img/exemples/tables/table-07.webp"
            image08="/assets/img/exemples/tables/table-08.webp"
            image09="/assets/img/exemples/tables/table-09.webp"
            image10="/assets/img/exemples/tables/table-10.webp"
            image11=""
            image12=""/>
    </div>
    <x-exemple-devis :page="$page"/>
@endsection
